trivia_questions = [
    {
        "question": "What is the chemical symbol for gold?",
        "choices": ["Au", "Ag", "Gd", "Go"],
        "answer": "Au",
        "category": "Science",
        "difficulty": "easy",
    },
    {
        "question": "Which planet is the largest in our solar system?",
        "choices": ["Earth", "Jupiter", "Saturn", "Neptune"],
        "answer": "Jupiter",
        "category": "Science",
        "difficulty": "easy",
    },
    {
        "question": "What is the capital city of Canada?",
        "choices": ["Toronto", "Vancouver", "Ottawa", "Montreal"],
        "answer": "Ottawa",
        "category": "Geography",
        "difficulty": "easy",
    },
    {
        "question": "In what year did the Berlin Wall fall?",
        "choices": ["1987", "1989", "1991", "1993"],
        "answer": "1989",
        "category": "History",
        "difficulty": "medium",
    },
    {
        "question": "Who wrote the novel 'Pride and Prejudice'?",
        "choices": ["Charlotte Brontë", "Jane Austen", "Mary Shelley", "Emily Dickinson"],
        "answer": "Jane Austen",
        "category": "Literature",
        "difficulty": "easy",
    },
    {
        "question": "Which ocean is the largest on Earth?",
        "choices": ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"],
        "answer": "Pacific Ocean",
        "category": "Geography",
        "difficulty": "easy",
    },
    {
        "question": "What does CPU stand for in computing?",
        "choices": ["Central Processing Unit", "Computer Personal Unit", "Core Power Utility", "Central Program Upload"],
        "answer": "Central Processing Unit",
        "category": "Technology",
        "difficulty": "easy",
    },
    {
        "question": "Which instrument typically has 88 keys?",
        "choices": ["Guitar", "Piano", "Violin", "Flute"],
        "answer": "Piano",
        "category": "Music",
        "difficulty": "easy",
    },
    {
        "question": "What is the smallest prime number?",
        "choices": ["0", "1", "2", "3"],
        "answer": "2",
        "category": "Math",
        "difficulty": "easy",
    },
    {
        "question": "Wimbledon is traditionally played on which type of court surface?",
        "choices": ["Clay", "Hard", "Grass", "Carpet"],
        "answer": "Grass",
        "category": "Sports",
        "difficulty": "easy",
    },
]
